jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test push using PAT
        env:
          GIT_TOKEN_CUSTOM: ${{ secrets.GIT_TOKEN_CUSTOM }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git checkout -b test-pat
          touch test.txt
          git add test.txt
          git commit -m "Test push using PAT [skip ci]"
          export GIT_ASKPASS=$(mktemp)
          echo "echo $GIT_TOKEN_CUSTOM" > $GIT_ASKPASS
          chmod +x $GIT_ASKPASS
          git push https://github.com/${{ github.repository }} HEAD:test-pat
          rm -f $GIT_ASKPASS
