[firebase_admin]
type = "service_account"
project_id = "eu-see-dashboard-7003c"
private_key_id = "56e80fdc01d357b15f150d4b6d789d77a9163416"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDmr73yq2gnUN1x
DCmj4PjLafj/xrPeg30kc85XZ6Y35NhjwEBSpCZeBPOWSZXDKtSX4iRrf/dmz9Eb
qykD6s96qwhh8GJNoFElfH3QQs+y+VE9kG27foDn1aW68NCiYwwXNpQcEFU9QGJz
213zmqVuxmmUQ73CabORWtd67SLRFGLnTHKFI7E6xJw2bZsKiPLTOlshmZnHB6Dn
VXQOUDdjuxZYPMpp8BbziXmYtIUbgixfysBXrjA7l3rLZH5RXAdda7nF1wL6BR19
Lm1xyth3ySXotlMuIyXd015wf+JE2UP7XN8UDBZkuuHzod3ssrArZ0JORzqouX5m
HHwNH82nAgMBAAECggEARlVvzwS2wUH0+iowqfAGOxLI4ccmASJK7enHEDwgYCtM
VIGBuxCkSAcvc3NlD3fIELTY0NPXzQdwpIR3gWO+tZJfAGlnt245P3oo6+3q4JEG
VYRrCH7l84leudQBcHlNbuhrmPDb5Ex0mAlaqFLOvKsO9q7+tL9AigFN8INLmb4O
xcqGGnvE77tvoHo3GDNxWEFy9e4Bbb89Hcox9jzuasmt9oucCFNongGgyJI8FCAB
RW/8H3GHR1Ea9nFWMcno5kmLRVIn9zX3YpTF/zKrv4R+TejLgiQlZp/cee8PtBVZ
WbgcjbA+eIeJS4MJ64J1cbpob38hvUlB7Nx2deQ4aQKBgQD1jRGFRdvflD6ExAxt
EGjLz3dCWzMdJUJP2wqA4dgHogF2zjK69t6g+4WOf/iY3ICYj3Koz8R+m3CnhSkT
LM7TUQRlIuiOZfA07wA1uXU0/FExXGsOi02vRdB4lFM1Mt5DW8DK2jO8Nc7gxBFF
FkyLL4XPQewxJDTsP1qtl42dCQKBgQDwgL7GXPX4sdALHC75tlGCbLnP02yMdS1O
RHmjs+EZzqaoj/HTY2tWMKqKBmtXPVvYOTSxJv7lBbZy710pxm2P4Zs7DYvVHhDx
Id+fUs4Liak4F+Wm515thQBnmhWHmaG2CdVOWXeleZvFzWB+7MbFpGJPFIj9gfFV
m4NMvBdxLwKBgQCxrMKZuaPQUpcuQCFxpWb+2n7D3/PLShOCbs9Z1JEZbMs8aRVi
HZGX0IeiRcze5uaR/XIM3lGi/tx0CrFe85QwabYRbEH0D6TQ2INBXJGHpm8llWbN
nlS214ByT3kpzEXxXWnSHjNDI3gvQQ/x+qGmMNvUzTGXmUhGDc2SQFAy6QKBgQDY
fAs9oxAF/Ii4d3YRcPuN2zCm0jkzdYaCnUChCpnlEQ8TS/7xuNw1iTj5ZS3aKXEz
AMtdayymGq5QZwYFRIf6q6l/ToJAJAA8DbGtSGwQFqorw9cEld951e63UwtuM+xM
YC2RiRcZ7I07T9M8bQW/gmi7plBpYT5LQOC/gc/YIQKBgDxVnW517Jx0mfxy9/EA
pxrHgFEHOxqCVz6ZLVM1ovKH1euZvAZwaauU0eXe2SNi3lRQAdp5XxxpQqHR0iaR
bu0osJuB1lJFlYwOpXF2EHDPAiqp3hAVq05Szd2UsmoBIiOz7gB2tfNG6zKnr6zv
dVp8Yg/PJjjpUXNlVG2buEt1
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@eu-see-dashboard-7003c.iam.gserviceaccount.com"
client_id = "117405000039375944276"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc@eu-see-dashboard-7003c.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[firebase]
apiKey = "AIzaSyArgwKMRd6jOXiHN6G-yI0wQWY196LIR8A"
authDomain = "eu-see-dashboard-7003c.firebaseapp.com"
databaseURL = "https://eu-see-dashboard-7003c-default-rtdb.firebaseio.com/"
projectId = "eu-see-dashboard-7003c"
storageBucket = "eu-see-dashboard-7003c.firebasestorage.app"
messagingSenderId = "531776985261"
appId = "1:531776985261:web:76679fbd6b6796f25f0e24"  # NOT used for Google OAuth

[oauth]
client_id = "257053101254-gq7nsikt4c3eguossapvgbmv7m7ans9t.apps.googleusercontent.com"        # ← use this for Google login
client_secret = "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T"
redirect_uri = "https://eesu-app.streamlit.app"

[access]
privileged_domains = ["gmail.com","cgiar.org"]

password = "supersecretkey123!"  # use a strong, random secret
